In [2]:
import numpy as np
import pandas as pd
import random

In [19]:
import numpy as np
import pandas as pd

# Create the features as a NumPy array with 20 rows and 5 columns
features = np.random.randint(6, size=(20, 5))

# Create the labels as a NumPy array with 20 elements
labels = np.random.randint(2, size=20)

# Create a dictionary with the feature and label arrays
data = {f"feature {i+1}": features[:,i] for i in range(5)}
data['labels'] = labels

# Create a Pandas DataFrame with the feature and label arrays
df = pd.DataFrame(data)


In [20]:
df


feature 1  feature 2  feature 3  feature 4  feature 5  labels
0           0          3          5          0          0       1
1           2          0          5          2          0       0
2           4          3          3          4          1       0
3           1          0          1          5          3       0
4           4          4          3          3          0       0
5           4          5          4          1          5       0
6           5          2          1          2          2       1
7           5          2          4          1          5       1
8           3          4          3          4          0       1
9           1          4          2          2          2       0
10          1          3          5          5          4       1
11          1          4          5          0          3       1
12          4          3          1          4          2       1
13          2          4          2          1          1       1
14          5          3          5          4          5       0
15          0          2          2          1          0       1
16          4          3          2          3          3       0
17          5          4          5          3          4       0
18          0          4          2          1          5       1
19          5          1          1          0          5       0

In [21]:
features_list = list(features)

In [22]:
labels_list = list (labels)

In [23]:
features_list

[array([0, 3, 5, 0, 0]),
 array([2, 0, 5, 2, 0]),
 array([4, 3, 3, 4, 1]),
 array([1, 0, 1, 5, 3]),
 array([4, 4, 3, 3, 0]),
 array([4, 5, 4, 1, 5]),
 array([5, 2, 1, 2, 2]),
 array([5, 2, 4, 1, 5]),
 array([3, 4, 3, 4, 0]),
 array([1, 4, 2, 2, 2]),
 array([1, 3, 5, 5, 4]),
 array([1, 4, 5, 0, 3]),
 array([4, 3, 1, 4, 2]),
 array([2, 4, 2, 1, 1]),
 array([5, 3, 5, 4, 5]),
 array([0, 2, 2, 1, 0]),
 array([4, 3, 2, 3, 3]),
 array([5, 4, 5, 3, 4]),
 array([0, 4, 2, 1, 5]),
 array([5, 1, 1, 0, 5])]

In [24]:
w1 = np.random.randn(3,5) * 0.01
w2 = np.random.randn(3,3) * 0.01
w3 = np.random.randn(1,3) * 0.01

b1 = np.zeros((3,1))
b2 = np.zeros((3,1))
b3 = np.zeros((1,1))

In [25]:
a0 = np.zeros((5,1))
a1 = np.zeros((3,1))
a2 = np.zeros((3,1))
a3 = np.zeros((1,1))
z1 = np.zeros((3,1))
z2 = np.zeros((3,1))
z3 = np.zeros((1,1))

In [55]:
print('w1', w1)
print('w2', w2)
print('w3', w3)

w1 [[ 1.58302508e-02  1.73055621e-02 -8.33510453e-05  4.88404344e-03
  -2.79817476e-03]
 [ 3.17871212e-03 -4.45282930e-03  5.89123166e-03  1.10903285e-03
   4.89872582e-03]
 [-6.60564901e-03  8.68040481e-04 -2.18391081e-02 -1.97517176e-02
   6.45944868e-03]]
w2 [[ 0.01943714  0.00459172 -0.00890106]
 [ 0.00131624 -0.03110848 -0.01463569]
 [-0.00235501  0.01066755  0.01312488]]
w3 [[-0.00019923  0.00371024 -0.00162017]]


In [26]:
labels

array([1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0])

In [18]:
a3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [28]:
# features variable contains all the training examples as a numpy array
# label variale contains the features
x = np.transpose(features)
y = np.transpose(labels)

#Forward Pass
a0 = x
z1 = np.dot(w1,a0) + b1
a1 = np.maximum(0,z1)
z2 = np.dot(w2,a1) + b2
a2 = np.maximum(0,z2)
z3 = np.dot(w3,a2) + b3
print(z3.shape)
a3 = 1/(1 + np.exp(-z3))






(1, 20)


In [56]:
a3

array([[0.49999993, 0.49999983, 0.49999987, 0.49999987, 0.49999985,
        0.49999982, 0.49999988, 0.49999974, 0.49999987, 0.49999991,
        0.4999998 , 0.49999986, 0.49999987, 0.4999999 , 0.49999972,
        0.49999996, 0.49999987, 0.49999977, 0.49999991, 0.49999981]])

In [57]:
y

array([[1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0]])

In [60]:
def mse(x,y):
    x = list(x)
    y = list(y)
    summ = 0
    for i,j in zip(x,y):
        summ += (i-j)**2
    print(summ)
    return summ/len(x)

print('Loss is: ', mse(a3[0],y[0]))

4.999999589339379
Loss is:  0.24999997946696895


In [33]:
y = y.reshape(1,20)

In [54]:
#BackProp
dZ3 = a3 - y

dW3 = np.dot(dZ3 , np.transpose(a2))/20
db3 = np.sum(dZ3, axis=1, keepdims=True)
temp1 = 1 * (z2>0)
dZ2 = np.dot(np.transpose(w3),dZ3) * temp1
dW2 = np.dot(dZ2 , np.transpose(a1))/20
db2 = np.sum(dZ2, axis=1, keepdims=True)
temp2 = 1 * (z1>0)
dZ1 = np.dot(np.transpose(w2),dZ2) * temp2
dW1 = np.dot(dZ1 , np.transpose(a0))/20
db1 = np.sum(dZ1, axis=1, keepdims=True)








In [69]:
learning_rate = 0.1
w3 = w3 - (learning_rate*dW3)
w2 = w2 - (learning_rate*dW2)
w1 = w1 - (learning_rate*dW1)
b3 = b3 - (learning_rate*db3)
b2 = b2 - (learning_rate*db2)
b1 = b1 - (learning_rate*db1)



In [70]:

x = np.transpose(features)
y = np.transpose(labels)

#Forward Pass
a0 = x
z1 = np.dot(w1,a0) + b1
a1 = np.maximum(0,z1)
z2 = np.dot(w2,a1) + b2
a2 = np.maximum(0,z2)
z3 = np.dot(w3,a2) + b3
print(z3.shape)
a3 = 1/(1 + np.exp(-z3))






(1, 20)


In [73]:
w1

array([[ 1.58302005e-02,  1.73055195e-02, -8.33613813e-05,
         4.88401322e-03, -2.79819481e-03],
       [ 3.17965039e-03, -4.45283936e-03,  5.89132924e-03,
         1.10957579e-03,  4.89912115e-03],
       [-6.60564901e-03,  8.68040481e-04, -2.18391081e-02,
        -1.97517176e-02,  6.45944868e-03]])

In [68]:
dW1

array([[ 4.56985799e-07,  3.87253205e-07,  9.39629686e-08,
         2.74761758e-07,  1.82224167e-07],
       [-8.52973824e-06,  9.14875452e-08, -8.87027033e-07,
        -4.93586132e-06, -3.59387158e-06],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00]])

In [35]:
a = np.array([1,2])

In [36]:
a/2

array([0.5, 1. ])

In [41]:
1*(a>1)

array([0, 1])